/* ============ EXERCISE LIBRARY ============
   History is keyed by these ids. Move an exercise between days,
   change its sets, or drop and re-add it — the history follows the id. */
const LIB={
 bench:{n:"Bench Press",g:"Chest",alts:["Dumbbell Bench","Machine Chest Press","Push-ups"],
  c:["Set up with shoulder blades pulled back and down into the bench — this protects the shoulder and gives you a stable base.","Lower the bar to the lower chest, not the neck. Elbows roughly 45° from your body, not flared straight out.","Keep both feet planted and don't bounce the bar off your chest."]},
 dbbench:{n:"Dumbbell Bench",g:"Chest",alts:["Machine Chest Press","Bench Press","Push-ups"],
  c:["Kick the dumbbells up off your knees as you lie back, rather than lifting them from the floor.","Lower until the handles are level with your chest, elbows about 45° from your body, then press up and slightly in.","Each arm works on its own, so the weaker side shows up — let it set the pace, and add weight only when both hit the reps."]},
 mchest:{n:"Machine Chest Press",g:"Chest",alts:["Dumbbell Bench","Bench Press","Push-ups"],
  c:["Set the seat so the handles line up with the middle of your chest, not your shoulders.","Keep your shoulder blades pinned back against the pad as you press — don't let the shoulders roll forward at the end.","The machine keeps you safe near failure, so this is a good one to push hard on the last set."]},
 incline:{n:"Dumbbell Incline",g:"Chest",alts:["Bench Press","Machine Chest Press","Incline Push-ups"],
  c:["Set the bench to about 30°. Steeper than that shifts the work to your shoulders instead of your upper chest.","Press up and slightly inward, stopping short of clanging the dumbbells together.","Control the lowering — that's where most of the muscle growth happens."]},
 decline:{n:"Dumbbell Decline",g:"Chest",alts:["Dumbbell Bench","Push-ups","Machine Chest Press"],
  c:["Lock your legs in securely before you take the dumbbells.","Lower to the lower chest with a slow, controlled tempo.","Ask for a hand passing the dumbbells up if they're heavy."]},
 dbfly:{n:"Dumbbell Fly",g:"Chest",alts:["Cable Fly","Pec Deck","Machine Fly"],
  c:["Keep a soft, fixed bend in the elbows throughout — the angle shouldn't change as you lower.","Go light. This is a stretch exercise, not a pressing one.","Stop the lowering when you feel a strong stretch across the chest, not when your arms are as wide as they'll go."]},
 pecdeck:{n:"Pec Deck",g:"Chest",alts:["Dumbbell Fly","Cable Fly","Machine Fly"],
  c:["Set the seat so the handles are at chest height and your elbows sit just below your shoulders.","Keep a slight bend in the elbows and bring the handles together by squeezing your chest, not by pulling with your hands.","Let the arms come back until you feel a stretch across the chest, under control — no bouncing off the stack."]},
 pushup:{n:"Push-ups",g:"Chest",alts:["Incline Push-ups","Dumbbell Bench","Machine Chest Press"],
  c:["Keep a straight line from head to heels — no sagging hips.","Elbows at roughly 45°, not flared to the sides.","Too easy? Elevate your feet. Too hard? Hands on a bench."]},
 ohp:{n:"Barbell Shoulder Press",g:"Shoulders",alts:["DB Shoulder Press","Machine Shoulder Press","Landmine Press"],
  c:["Brace your abs and squeeze your glutes — this stops the lower back arching as you press.","Move your head back slightly so the bar travels straight up past your face.","Finish with the bar over the middle of your foot, not out in front."]},
 dbshoulder:{n:"DB Shoulder Press",g:"Shoulders",alts:["Barbell Shoulder Press","Machine Shoulder Press","Landmine Press"],
  c:["Start with the dumbbells at ear height, elbows slightly forward rather than straight out to the sides.","Press up without letting your lower back arch.","Seated with a back support is the easier place to start."]},
 mshoulder:{n:"Machine Shoulder Press",g:"Shoulders",alts:["DB Shoulder Press","Barbell Shoulder Press","Landmine Press"],
  c:["Adjust the seat so the handles start at about shoulder height.","Keep your back against the pad and press straight up without shrugging.","Lower until your hands are near shoulder level, then press again — full range every rep."]},
 lateral:{n:"Lateral Raises",g:"Shoulders",alts:["Cable Lateral Raise","Machine Lateral Raise","Band Lateral Raise"],
  c:["Go deliberately light — this is the exercise people most often ruin with too much weight.","Lead with your elbows, raising to shoulder height and no higher.","No swinging. If your body is moving to get the weight up, drop the weight."]},
 frontraise:{n:"Plate / Front Raises",g:"Shoulders",alts:["DB Front Raise","Landmine Raise","Cable Front Raise"],
  c:["Raise to about eye level with a controlled tempo.","Keep your torso still — resist leaning back to help the weight up.","Light weight, high control."]},
 facepull:{n:"Face Pulls",g:"Shoulders",alts:["Reverse Pec Deck","Band Pull-Apart","Rear Delt Fly"],
  c:["Set the cable at roughly face height and pull towards your forehead, not your chin.","Aim to finish with your hands beside your ears and elbows high.","This one's for shoulder health — prioritise the squeeze over the weight."]},
 bbrow:{n:"Barbell Row",g:"Back",alts:["Single-arm DB Row","Chest-Supported Row","T-Bar Row"],
  c:["Hinge to about 45° with a flat back — the spine stays neutral throughout, never rounded.","Pull the bar to your lower ribs or belly button, leading with your elbows.","Don't jerk with your lower back to move the weight. If you have to, it's too heavy."]},
 latpulldown:{n:"Lat Pulldown",g:"Back",alts:["Assisted Pull Ups","Band-Assisted Pull Ups","DB Pullover"],
  c:["Pull the bar to your upper chest, not behind your neck.","Start each rep by driving your shoulders down, then bend the elbows.","Lean back slightly and hold that angle — don't rock back and forth."]},
 cablerow:{n:"Cable Row",g:"Back",alts:["Single-arm DB Row","Chest-Supported Row","Inverted Row"],
  c:["Sit tall with a slight knee bend and keep your chest up.","Pull to your stomach, squeezing the shoulder blades together at the end.","Let the weight stretch your lats on the return, but don't let your back round."]},
 dbrow:{n:"Single-arm DB Row",g:"Back",alts:["Cable Row","Chest-Supported Row","Inverted Row"],
  c:["Knee and hand on a bench, back flat and roughly parallel to the floor.","Pull the dumbbell to your hip, not straight up to your shoulder.","Avoid twisting your torso to get extra range."]},
 csrow:{n:"Chest-Supported Row",g:"Back",alts:["T-Bar Row","Cable Row","Single-arm DB Row"],
  c:["Chest stays glued to the pad for every rep — if it lifts off, the weight is too heavy.","Pull the elbows back and squeeze the shoulder blades together at the top.","Let the arms straighten fully at the bottom for a stretch, without letting the shoulders roll forward."]},
 pullup:{n:"Assisted Pull Ups",g:"Back",alts:["Lat Pulldown","Band-Assisted Pull Ups","Inverted Row"],
  c:["Start from a full hang with shoulders engaged, not fully slack.","Pull until your chin clears the bar, then lower under control.","Use as little assistance as you can manage while still hitting the reps."]},
 pullover:{n:"DB Pullover",g:"Back",alts:["Lat Pulldown","Cable Pullover","Assisted Pull Ups"],
  c:["Keep the elbows slightly bent and fixed.","Lower until you feel the stretch through the lats and ribs, then pull back over.","Keep your ribs down rather than letting the back arch."]},
 squat:{n:"Barbell Squat",g:"Legs",alts:["Goblet Squat","Leg Press","Bulgarian Split Squat"],
  c:["Brace as though about to be punched in the stomach, and hold that through the rep.","Push your knees out in line with your toes — don't let them cave in.","Descend to at least parallel if your mobility allows, keeping your heels planted throughout."]},
 goblet:{n:"Goblet Squat",g:"Legs",alts:["Barbell Squat","Leg Press","Bulgarian Split Squat"],
  c:["Hold the weight at chest height, elbows tucked in.","Sit down between your hips and keep your chest tall.","A great place to learn squat depth without a bar on your back."]},
 frontsquat:{n:"Front Squat",g:"Legs",alts:["Goblet Squat","Leg Press","Barbell Squat"],
  c:["Bar sits on the front of the shoulders, elbows driven high so the upper arms stay near parallel to the floor.","Stay upright — if your elbows drop, the bar rolls forward. This is a quad and upper-back exercise as much as a squat.","Lighter than your back squat is normal. Start well under it and build."]},
 legpress:{n:"Leg Press",g:"Legs",alts:["Hack Squat","Goblet Squat","Walking Lunges"],
  c:["Start lighter than you think and add weight each set — the first set is a build-up.","Lower until your knees reach about 90°. Don't let your lower back peel off the pad.","Never lock the knees out hard at the top."]},
 lunge:{n:"Walking Lunges",g:"Legs",alts:["Bulgarian Split Squat","Goblet Squat","Leg Press"],
  c:["Take a long enough step that your front shin stays fairly vertical.","Drop the back knee towards the floor rather than lunging forward.","Keep your torso upright and start bodyweight-only."]},
 bulgarian:{n:"Bulgarian Split Squat",g:"Legs",alts:["Walking Lunges","Goblet Squat","Leg Press"],
  c:["Rear foot on a bench, front foot far enough forward to keep the shin vertical.","Go straight down, not forward.","Brutal for how light it feels — start with bodyweight."]},
 deadlift:{n:"Deadlift",g:"Legs",alts:["Trap Bar Deadlift","RDLs","Rack Pull"],
  c:["Bar over the middle of your foot, shins close to it, hips higher than your knees and lower than your shoulders.","Take the slack out of the bar and brace hard before it leaves the floor. Push the floor away rather than pulling with your back.","Lock out by standing tall — don't lean back. Lower under control; don't drop it and don't bounce the next rep."]},
 rdl:{n:"RDLs",g:"Legs",alts:["Dumbbell RDL","Single-leg RDL","Good Mornings"],
  c:["Push your hips back rather than bending your knees — this is a hinge, not a squat.","Keep the bar close to your legs, almost dragging down the thighs.","Stop when you feel a strong hamstring stretch. Back stays flat the whole way; never round it."]},
 dbrdl:{n:"Dumbbell RDL",g:"Legs",alts:["Leg Curls","Single-leg RDL","RDLs"],
  c:["Dumbbells in front of your thighs, soft knees. Push your hips back — it's a hinge, not a squat.","Keep the dumbbells brushing your legs on the way down, back flat the whole time.","Stop at a strong hamstring stretch (usually around mid-shin), then drive the hips forward to stand tall."]},
 legcurl:{n:"Leg Curls",g:"Legs",alts:["Single-leg RDL","Hip Thrust","Good Mornings"],
  c:["Keep your hips pressed into the pad throughout.","Squeeze at the top and lower slowly — resist the weight on the way back.","Don't let the weight stack slam down between reps."]},
 legext:{n:"Leg Extensions",g:"Legs",alts:["Goblet Squat","Walking Lunges","Leg Press"],
  c:["Line the machine's pivot up with your knee before you start.","Pause briefly at the top with the quads squeezed.","Moderate weight — jerking heavy loads here is hard on the knees."]},
 hipthrust:{n:"Hip Thrust",g:"Legs",alts:["Glute Bridge","RDLs","Single-leg RDL"],
  c:["Shoulder blades on the bench, chin tucked slightly.","Drive through your heels and squeeze the glutes hard at the top.","Stop at a flat torso — don't over-arch the lower back."]},
 calf:{n:"Calf Raises",g:"Legs",alts:["Seated Calf Raise","Leg Press Calf Raise","Single-leg Calf Raise"],
  c:["Full range: deep stretch at the bottom, high squeeze at the top.","Pause a beat at both ends rather than bouncing.","Calves respond well to higher reps."]},
 pushdown:{n:"Tricep Pushdown",g:"Arms",alts:["Overhead Extension","Rope Pushdown","Close-Grip Push-ups"],
  c:["Keep your elbows pinned to your sides — only the forearms move.","Fully straighten the arms and squeeze at the bottom.","Stand slightly back from the stack, torso still."]},
 ohext:{n:"Overhead Extension",g:"Arms",alts:["Skull Crusher","Rope Pushdown","Tricep Pushdown"],
  c:["Keep your elbows pointing forward and close to your head.","Lower behind your head until you feel the stretch, then extend.","Ribs down — don't let the lower back arch."]},
 skull:{n:"Skull Crusher",g:"Arms",alts:["Overhead Extension","Rope Pushdown","Close-Grip Bench"],
  c:["Light weight and strict form — this one punishes ego lifting and elbows.","Lower to just above your forehead or slightly behind it, elbows steady.","An EZ bar is kinder on the wrists than a straight bar."]},
 dips:{n:"Dips",g:"Arms",alts:["Bench Dips","Close-Grip Push-ups","Rope Pushdown"],
  c:["Lean forward to bias the chest; stay upright to bias the triceps.","Lower until your upper arms reach about parallel — no deeper if your shoulders complain.","Use the assisted machine if bodyweight is too much for now."]},
 hammer:{n:"Hammer Curl",g:"Arms",alts:["Dumbbell Curl","Cable Curl","Incline DB Curl"],
  c:["Palms face each other throughout — thumbs up, like holding a hammer.","Keep your elbows at your sides and don't swing.","Lower slowly rather than dropping the weight."]},
 dbcurl:{n:"Dumbbell Curl",g:"Arms",alts:["Hammer Curl","Cable Curl","Barbell Curl"],
  c:["Elbows stay pinned at your sides.","Supinate — turn your palm up — as you curl.","No body English; if you're rocking, go lighter."]},
 bbcurl:{n:"Barbell Curl",g:"Arms",alts:["Dumbbell Curl","Cable Curl","Preacher Curl"],
  c:["Stand tall with elbows tucked in.","Curl without swinging your torso back.","An EZ bar is easier on the wrists if a straight bar aggravates them."]},
 preacher:{n:"Preacher Curl",g:"Arms",alts:["Concentration Curl","Cable Curl","Barbell Curl"],
  c:["Armpits snug against the top of the pad.","Don't fully snap the elbow straight at the bottom — keep slight tension.","Control the lowering; this position makes the stretch intense."]},
 cablecurl:{n:"Cable Curl",g:"Arms",alts:["Hammer Curl","Dumbbell Curl","Preacher Curl"],
  c:["Constant tension is the advantage here — don't rest at the bottom.","Elbows fixed at your sides.","Squeeze hard at the top of each rep."]},
 concentration:{n:"Concentration Curl",g:"Arms",alts:["Preacher Curl","Dumbbell Curl","Cable Curl"],
  c:["Elbow braced against the inside of your thigh.","Curl slowly and squeeze at the top.","One arm at a time, no swinging."]}
};

